--odps sql 
--********************************************************************--
--author:李苑
--create time:2021-08-24 09:30:51
--********************************************************************--


SELECT DISTINCT EVENT FROM tr_login_mc;
SELECT DISTINCT RESULT FROM tr_login_mc;

WITH BASE AS
(
SELECT *
     , CAST(CONCAT(SUBSTR(DATETRUNC(create_time, 'dd'), 1, 10), ' ', '00:00:00') AS DATETIME) AS BENCHMARK_0
     , CAST(CONCAT(SUBSTR(DATETRUNC(create_time, 'dd'), 1, 10), ' ', '06:00:00') AS DATETIME) AS BENCHMARK_1
     , CAST(CONCAT(SUBSTR(DATETRUNC(create_time, 'dd'), 1, 10), ' ', '12:00:00') AS DATETIME) AS BENCHMARK_2
     , CAST(CONCAT(SUBSTR(DATETRUNC(create_time, 'dd'), 1, 10), ' ', '18:00:00') AS DATETIME) AS BENCHMARK_3
     , CAST(CONCAT(SUBSTR(DATETRUNC(create_time, 'dd'), 1, 10), ' ', '23:59:59') AS DATETIME) AS BENCHMARK_4
 FROM tr_login_mc
WHERE CREATE_TIME >= CAST(DATEADD(DATETRUNC(NOW(), 'dd'), -180, 'dd') AS DATETIME)   -------   半年之前的登陆记录
  AND LOGIN_NAME IS NOT NULL
)
, F AS
(
    SELECT *
        , CASE WHEN CREATE_TIME >= BENCHMARK_0 AND CREATE_TIME < BENCHMARK_1 THEN BENCHMARK_1
                WHEN CREATE_TIME >= BENCHMARK_1 AND CREATE_TIME < BENCHMARK_2 THEN BENCHMARK_2
                WHEN CREATE_TIME >= BENCHMARK_2 AND CREATE_TIME < BENCHMARK_3 THEN BENCHMARK_3
                WHEN CREATE_TIME >= BENCHMARK_3 AND CREATE_TIME < BENCHMARK_4 THEN BENCHMARK_4
                END AS TIME_NODE
    FROM BASE
)
SELECT LOGIN_NAME
     , TIME_NODE
    ------ 使用的IP数量
     , COUNT(DISTINCT CLIENT_IP) AS CNT_IP    
    ------ 登陆状态
     , SUM(CASE WHEN EVENT = 0 AND RESULT = 0 THEN 1 ELSE 0 END) AS CNT_LOGIN_SUCCESS    
     , SUM(CASE WHEN EVENT = 0 AND RESULT = 1 THEN 1 ELSE 0 END) AS CNT_LOGIN_FAIL
    ------ 登出状态
     , SUM(CASE WHEN EVENT = 1 AND RESULT = 0 THEN 1 ELSE 0 END) AS CNT_LOGOUT_SUCCESS
     , SUM(CASE WHEN EVENT = 1 AND RESULT = 1 THEN 1 ELSE 0 END) AS CNT_LOGOUT_FAIL
    ------ 密码修改状态
     , SUM(CASE WHEN EVENT = 3 AND RESULT = 0 THEN 1 ELSE 0 END) AS CNT_PWD_RESET_SUCCESS
     , SUM(CASE WHEN EVENT = 3 AND RESULT = 1 THEN 1 ELSE 0 END) AS CNT_PWD_RESET_FAIL
    ------ 保密问题设置
     , SUM(CASE WHEN EVENT = 4 AND RESULT = 0 THEN 1 ELSE 0 END) AS CNT_SETUP_SUCCESS
     , SUM(CASE WHEN EVENT = 4 AND RESULT = 1 THEN 1 ELSE 0 END) AS CNT_SETUP_FAIL
    ------ 图标点击
     , SUM(CASE WHEN EVENT = 5 AND RESULT = 0 THEN 1 ELSE 0 END) AS CNT_APP_SUCCESS
     , SUM(CASE WHEN EVENT = 5 AND RESULT = 1 THEN 1 ELSE 0 END) AS CNT_APP_FAIL
     , COUNT(DISTINCT MEMO) AS CNT_APP
FROM F 
GROUP BY LOGIN_NAME, TIME_NODE
-- HAVING LOGIN_NAME = 'liyuan-102'
ORDER BY LOGIN_NAME, TIME_NODE;


--SELECT * FROM tr_login_mc WHERE login_name = 'liyuan-102';